apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "name" . }}
    team: aura
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "name" . }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        environment: default
        team: aura
      name: {{ template "fullname" . }}
      namespace: {{ .Release.Namespace }}
    spec:
      serviceAccount: {{ template "fullname" . }}
      containers:
      - env:
        - name: APP_NAME
          value: {{ template "name" . }}
        - name: NODE_ENV
          value: production
        image: {{ .Values.image }}:{{ .Values.version }}
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command:
              - pidof
              - node
        livenessProbe:
          exec:
            command:
              - pidof
              - node
        name: {{ template "fullname" . }}
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
