apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin #{{ template "fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  verbs: ["list", "get",  "watch"]
  resources:
    - pods
    - configmaps
    - endpoints
    - resourcequotas
    - serviceaccounts
    - secrets
    - services
- apiGroups: ["extensions"]
  verbs: ["list", "get",  "watch"]
  resources:
    - ingresses
- apiGroups: ["apps"]
  verbs: ["list", "get",  "watch"]
  resources:
    - deployments
    - replicasets
    - statefulsets
- apiGroups: ["autoscaling"]
  verbs: ["list", "get",  "watch"]
  resources:
    - horizontalpodautoscalers
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
    - role
  verbs: ["create", "get",  "list", "update", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
