version: 2
jobs:
  test-only:
    docker:
      - image: circleci/node:10-stretch
    steps:
      - checkout
      - run:
          name: Run tests with JUnit as reporter
          command: npm install
      - run:
          name: Run tests with JUnit as reporter
          environment:
            JEST_JUNIT_OUTPUT: "reports/js-test-results.xml"
          command: $(npm bin)/jest --ci --reporters=default --reporters=jest-junit
      - store_artifacts:
          path: "reports/js-test-results.xml"
          prefix: tests
      - store_test_results:
          path: "reports/js-test-results.xml"
  publish-docker-hub:
    docker:
      - image: circleci/node:10-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker build
          command: |
            docker build -t app .
      - deploy:
          name: docker push
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git_tag=$(git describe --tags)
              echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin
              docker tag app "navikt/terje:${CIRCLE_SHA1}"
              docker push "navikt/terje:${CIRCLE_SHA1}"
              docker tag app "navikt/terje:${git_tag}"
              docker push "navikt/terje:${git_tag}"
            fi
workflows:
  version: 2
  main:
    jobs:
      - test-only:
          filters:
            tags:
              ignore: /^.+$/
      - publish-docker-hub:
          filters:
            tags:
              only: /^.+$/
            branches:
              ignore: /.*/
